name: Release
on:
  push:
    branches:
      - master
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v2.4.0
        with:
          node-version: 14
          cache: yarn
      - name: Install Yarn dependencies
        run: yarn install
      - name: Release
        env:
          GIT_AUTHOR_NAME: "oblakbot"
          GIT_AUTHOR_EMAIL: "sibin.grasic+bot@oblak.studio"
          GIT_COMMITTER_NAME: "oblakbot"
          GIT_COMMITTER_EMAIL: 'sibin.grasic+bot@oblak.studio'
          GITHUB_TOKEN: ${{ secrets.OBLAK_BOT_TOKEN }}
        run: yarn run semantic-release

